apiVersion: 0.3.0
environments:
  kubeflow-ci:
    destination:
      namespace: kubeflow-test-infra
      server: https://35.185.54.227
    k8sVersion: v1.7.0
    path: kubeflow-ci
  releasing:
    destination:
      namespace: kubeflow-releasing
      server: https://35.226.49.107
    k8sVersion: v1.7.0
    path: releasing
kind: ksonnet.io/app
#libraries:
#  kubeflow/core:
#    name: core
#    registry: kubeflow
#    version: ""
name: test-infra
registries:
  incubator:
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
  kubeflow:
    protocol: github
    uri: github.com/kubeflow/kubeflow/tree/master/kubeflow
version: 0.0.1
