# Just for local test
appAddress: http://localhost:8080
defaultApp:
  packages:
    - argo
    - common
    - examples
    - gcp
    - jupyter
    - katib
    - metacontroller
    - modeldb
    - mpi-job
    - pipeline
    - pytorch-job
    - seldon
    - tensorboard
    - tf-serving
    - tf-training
  components:
    # ordering is important
    - metacontroller
    - ambassador
    - argo
    - centraldashboard
    - cert-manager
    - cloud-endpoints
    - gpu-driver
    - iap-ingress
    - jupyter-web-app
    - katib
    - notebook-controller
    - pipeline
    - pytorch-operator
    - tf-job-operator
  componentParams:
    cert-manager:
      - name: acmeEmail
        # TODO change value on the fly: use your email for ssl cert
        value: johnDoe@acme.com
        initRequired: true
    iap-ingress:
      - name: ipName
        # TODO change value on the fly: value of ipName need to match resource name in deployment entry.
        value: ipName
        initRequired: true
      - name: hostname
        # TODO change value on the fly: replace with user-provide parameters. This need to be fully qualified domain name to use with ingress.
        value: <deployName>.endpoints.<project>.cloud.goog
        initRequired: true
    cloud-endpoints:
      - name: secretName
        value: admin-gcp-sa
    spartakus:
      - name: usageId
        value: <randomly-generated-id>
        initRequired: true
      - name: reportUsage
        value: "true"
        initRequired: true
    notebook-controller:
      - name: injectGcpCredentials
        value: "true"
  platform: gcp
