steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/${_REGISTRY}/profile-controller:${_TAG}'
      - '.'
images: ['gcr.io/${_REGISTRY}/profile-controller:${_TAG}']